name: CI

Install: 
$ git clone https://github.com/maldevel/IPGeoLocation

$ cd IPGeoLocation

$ chmod +x *

$ pip install -r requirements.txt

jobs:
  build:

    runs-on: ipgeolocation.py

    steps:
    - uses: actions/ check location of your objetive
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
